Update of config files to includes sidebar menu by default
georchestra/mapstore2-georchestra pull request #526
Opened 2022-05-10 09:00 UTC by alexander-fedorenko

Missing part of the changes related to the updated layout. 
With the applied changes sidebar menu will be active by default for desktop on map viewer.
Context wizard plugin dependencies are updated.

2022-05-10 09:07 UTC, offtherailz requested changes
Accordingly to the migration [guidelines](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#replacing-burgermenu-with-sidebarmenu)
- [ ] StreetView dependencies have to be changed into SidebarMenu
- [ ] BurgerMenu have to be visible

2022-05-10 09:07 UTC, offtherailz commented on configs/pluginsConfig.json
> +        "Toolbar"
I think it needs to be modified this way.
```suggestion
        "SidebarMenu"
```

2022-05-10 09:11 UTC, offtherailz approved these changes

2022-05-10 09:29 UTC, merged

2022-06-20 15:08 UTC, landryb commented
@alexander-fedorenko is it intended to still use the `BurgerMenu` plugin in geostory/dashboards/mobile views ?

2022-06-20 15:54 UTC, tdipisa commented
> @alexander-fedorenko @tdipisa is it intended to still use the `BurgerMenu` plugin in geostory/dashboards/mobile views ?

yes

> **edit**: while here i noticed that the `About` plugin has `"showIn": ["BurgerMenu"]` in its config, unsure if that's also expected

where sorry?

2022-06-20 16:27 UTC, alexander-fedorenko commented
@tdipisa it's in localConfig.json
@landryb Thanks, you're right, this setting makes "About" button appear only when BurgerMenu is in use. We'll update localConfig.json to fix this behavior.