#651: Update MS to latest version (Phase III)
georchestra/mapstore2-georchestra pull request #653
Opened 2023-09-29 10:33 UTC by dsuren1

### Description
This PR updates MS submodule to latest of `2023.02.xx`

### Issue
- #651 

<details>
<summary>

### Testing

</summary>

**Note**: `zoomToLayer` is set to `false` for Catalog plugin (existing config) (COG layer won't zoom to extent when added with bbox)

</details>

2023-09-29 11:34 UTC, landryb commented
fwiw i've been able to deploy the debian package from https://github.com/georchestra/mapstore2-georchestra/actions/runs/6350369110 on a demo instance and i'm testing COG layers working fine there, including geosolutions-it/MapStore2#9469 (once you remember to tick *Télécharger les métadonnées du fichier lors de la recherche* in the catalog entry advanced options)

2023-10-02 16:34 UTC, offtherailz requested changes
Please : 
- [ ] Please update to the latest fixes coming up tomorrow. We have some fixes that we have to port. 
- [ ] pluginsConfig.json seems a little misaligned. In particular there are some correct differences, but also some misalignments that we could fix
    - swipe plugin missing as child of TOC
    - Settings do not have child version plugin anymore
    - other differences are correct, so we should not align them (e.g. Login - Version, different confiuguration for docs etc...)
    - mapviews and LongitudinalProfile seems to be removed in favor of GeoProcessing. It is a desired change ?

2023-10-03 05:37 UTC, dsuren1 commented
@offtherailz 
>   * swipe plugin missing as child of TOC

I'm not sure if this was intended, as these changes have been present for a long time. So I preferred to not add it. 
(_Anyway, I have added it now, as requested_)

>   * Settings do not have child version plugin anymore

This project has a custom version plugin and preferred to be in settings. 

>   * mapviews and LongitudinalProfile seems to be removed in favor of GeoProcessing. It is a desired change ?

No. probably overwritten when replacing contents from compare tool. (_Added now_)

2023-10-03 08:08 UTC, dsuren1 commented
@offtherailz 
> Please update to the latest fixes coming up tomorrow. We have some fixes that we have to port.

I have updated to latest MS. Are there still some fixes expected to be in today?

2023-10-03 08:29 UTC, tdipisa commented
Just [one](https://github.com/geosolutions-it/MapStore2/pull/9537) @dsuren1 I will let you know as soon as the build is finished.

2023-10-03 13:14 UTC, offtherailz approved these changes

2023-10-03 13:37 UTC, merged