#714: Project update to the latest MapStore 2024.02
georchestra/mapstore2-georchestra pull request #715
Opened 2024-10-15 13:12 UTC by dsuren1

### Description
This PR updates the MS submodules to `2024.02.xx` and aligns the configuration while preserving project specific configs

### Issue
- #714 

> [!NOTE]
An empty `favicon.ico` file has been added to prevent build failures caused by an invalid path. Based on this [PR](https://github.com/georchestra/mapstore2-georchestra/pull/677), assuming the script will replace the favicon path, no further action is required

### DB Changes
Follow the migration details with respect to DB/schema changes:
In detail migration information is available [here](https://docs.mapstore.geosolutionsgroup.com/en/v2024.01.00/developer-guide/mapstore-migration-guide/#database-update) 

  **POSTGRESQL** 
   - https://github.com/geosolutions-it/geostore/blob/master/doc/sql/migration/postgresql/postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
   
  **ORACLE**
  - https://github.com/geosolutions-it/geostore/blob/master/doc/sql/migration/oracle/oracle-migration-from-v.2.0.0-to-v2.1.0.sql
  
  **H2**
  - https://github.com/geosolutions-it/geostore/blob/master/doc/sql/migration/h2/h2-migration-from-v.2.0.0-to-v2.1.0.sql

2024-10-18 15:12 UTC, offtherailz requested changes
Here the issues found 

#### Verified issues

- [ ] [Restructuring of Login and Home in Dashboard page](https://docs.mapstore.geosolutionsgroup.com/en/v2024.02.00/developer-guide/mapstore-migration-guide/#restructuring-of-login-and-home-in-dashboard-page) has not been applied. Login should not be added, but the sidebar is missing. 
![image](https://github.com/user-attachments/assets/321ce5ad-4e7f-4893-ad55-584aa4351d6f)
 - [ ] [Adding spatial filter to dashboard widgets](https://docs.mapstore.geosolutionsgroup.com/en/v2024.02.00/developer-guide/mapstore-migration-guide/#adding-spatial-filter-to-dashboard-widgets) I don't see the changes in localConfig.json for this. I was not able to verify, becasue I'm not being able to login.

#### Not verified 
- [ ] I wasn't able to test login with usual test_env. So I'm not sure if user integration works. As far as I can see, there no simple way to test it. Maybe intalling georchestra locally with docker.
 - [ ] [Maven project update](https://docs.mapstore.geosolutionsgroup.com/en/v2024.02.00/developer-guide/mapstore-migration-guide/#maven-project-update) not done, does ntot make the application break, but maybe it is better to do this update for future work.


#### Points to make notice to the client

From migration guidelines.

 - [Enable showing credits/attribution text in Print config](https://docs.mapstore.geosolutionsgroup.com/en/v2024.02.00/developer-guide/mapstore-migration-guide/#enable-showing-creditsattribution-text-in-print-config) and [Print config file update](https://docs.mapstore.geosolutionsgroup.com/en/v2024.02.00/developer-guide/mapstore-migration-guide/#print-config-file-update) can be important, because they should have customized their print template.
 - [Using elevation layer type instead of wms layer with useForElevation property](https://docs.mapstore.geosolutionsgroup.com/en/v2024.02.00/developer-guide/mapstore-migration-guide/#using-elevation-layer-type-instead-of-wms-layer-with-useforelevation-property). May require a manual update of contexts from UI, if 3D is used.
- [ ] [Database update](https://docs.mapstore.geosolutionsgroup.com/en/v2024.02.00/developer-guide/mapstore-migration-guide/#database-update) this should work, but they have to make sure on their customization properties files if they didn't set this option to validate. This has been highlighted by @dsuren1 in PR description
```

2024-10-22 10:50 UTC, offtherailz approved these changes
I fixed duplicated spring security issues and other issues with missing copied files.

Needs to be tested in dev environment for ldap connection .

2024-10-22 14:18 UTC, tdipisa commented
@offtherailz 

> I fixed duplicated spring security issues and other issues with missing copied files.
> 
> Needs to be tested in dev environment for ldap connection .

better to avoid exclusions imo and use the mapstore-services SNAPSHOT which has the spring sec fix. In 2 weeks we will release the next minor version so I dont think it is a big deal to use a stable SNAPSHOT for not in master branch here :-)

2024-10-22 15:12 UTC, tdipisa approved these changes

2024-10-22 15:12 UTC, merged